### ISSUE TITLE
make install 到安装caffe那一步时报错

### ISSUE THREAD

**Issue by cosimo17** [oraoto/learn_ml#2]
make install 到安装caffe那一步时报错，请问如何跳过安装caffe和跳过系统检查？我只需要tensorflow

**Comment by oraoto** [comment]
@cosimo17 不好意思，没有watch这个仓库，所以现在才回复。

我只跳过了系统检查，然后自己安装了caffe。

NCS现在有提供Dockerfile，直接用就docker就可以了。
