### ISSUE TITLE
关于编译模型时的问题

### ISSUE THREAD

**Issue by cosimo17** [oraoto/learn_ml#3]
您好。按照你的minst的代码，编译时报错。
The name input:0 refers a tensor which does not exist.
请问如何解决？

**Comment by oraoto** [comment]
我还用了一个修改过的[TensorFlowParser.py](https://gist.github.com/oraoto/7656c7593b5bc7e481118e8c167d4d13)。

**Comment by oraoto** [comment]
NCSDK 2发布一段时间了，建议迁移，这里的旧的代码就不维护了。
